// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-cD-1laTziZda7hJHOkhFK1mm4b0AqL4',
    appId: '1:285615626239:web:e16a1671cad966d7eab9ca',
    messagingSenderId: '285615626239',
    projectId: 'chat-app-41a9a',
    authDomain: 'chat-app-41a9a.firebaseapp.com',
    storageBucket: 'chat-app-41a9a.firebasestorage.app',
    measurementId: 'G-VSVCERTDP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV8z_pv5bTwogoxec7wV54jOAvDJxBLxU',
    appId: '1:285615626239:android:4cefd62ac381be14eab9ca',
    messagingSenderId: '285615626239',
    projectId: 'chat-app-41a9a',
    storageBucket: 'chat-app-41a9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjE7esg1sxKmYihrsIiNcU8v-h-1ZyNg4',
    appId: '1:285615626239:ios:ca4053c6dde1f3f6eab9ca',
    messagingSenderId: '285615626239',
    projectId: 'chat-app-41a9a',
    storageBucket: 'chat-app-41a9a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjE7esg1sxKmYihrsIiNcU8v-h-1ZyNg4',
    appId: '1:285615626239:ios:ca4053c6dde1f3f6eab9ca',
    messagingSenderId: '285615626239',
    projectId: 'chat-app-41a9a',
    storageBucket: 'chat-app-41a9a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-cD-1laTziZda7hJHOkhFK1mm4b0AqL4',
    appId: '1:285615626239:web:2d446670ff060bf3eab9ca',
    messagingSenderId: '285615626239',
    projectId: 'chat-app-41a9a',
    authDomain: 'chat-app-41a9a.firebaseapp.com',
    storageBucket: 'chat-app-41a9a.firebasestorage.app',
    measurementId: 'G-J8HHG8QF2E',
  );
}
